//! CRC-64/ECMA checksum for sink round-trip verification.
//!
//! Dependency-free: the 256-entry table is generated by a `const fn`, so
//! there is no build script and no static blob to audit.

const POLY: u64 = 0xC96C_5795_D787_0F42;

/// The CRC-64/ECMA lookup table, generated at compile time.
const TABLE: [u64; 256] = build_table();

const fn build_table() -> [u64; 256] {
    let mut table = [0u64; 256];
    let mut i = 0;
    while i < 256 {
        let mut crc = i as u64;
        let mut j = 0;
        while j < 8 {
            if crc & 1 == 1 {
                crc = (crc >> 1) ^ POLY;
            } else {
                crc >>= 1;
            }
            j += 1;
        }
        table[i] = crc;
        i += 1;
    }
    table
}

/// Checksum of `bytes` under CRC-64/ECMA.
#[must_use]
pub fn checksum(bytes: &[u8]) -> u64 {
    let mut crc = u64::MAX;
    for &b in bytes {
        let idx = ((crc & 0xFF) as u8 ^ b) as usize;
        crc = TABLE[idx] ^ (crc >> 8);
    }
    !crc
}

/// A running checksum updated one block at a time (for streaming uploads).
#[derive(Debug, Clone, Copy)]
pub struct Rolling {
    crc: u64,
}

impl Rolling {
    /// A fresh accumulator.
    #[must_use]
    pub const fn new() -> Self {
        Self { crc: u64::MAX }
    }

    /// Feeds one block.
    pub fn update(&mut self, bytes: &[u8]) {
        for &b in bytes {
            let idx = (self.crc as u8 ^ b) as usize;
            self.crc = TABLE[idx] ^ (self.crc >> 8);
        }
    }

    /// The finished checksum.
    #[must_use]
    pub const fn finish(self) -> u64 {
        !self.crc
    }
}

impl Default for Rolling {
    fn default() -> Self {
        Self::new()
    }
}

impl Rolling {
    /// Resumes from a finished checksum (un-inverts the final xor).
    pub(crate) const fn from_finished(checksum: u64) -> Self {
        Self { crc: !checksum }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_vector() {
        // CRC-64/ECMA check value for "123456789".
        assert_eq!(checksum(b"123456789"), 0x995D_C9BB_DF19_39FA);
    }

    #[test]
    fn rolling_matches_oneshot() {
        let data: Vec<u8> = (0..10_000u32)
            .map(|i| i.wrapping_mul(2654435761) as u8)
            .collect();
        let mut r = Rolling::new();
        for chunk in data.chunks(4096) {
            r.update(chunk);
        }
        assert_eq!(r.finish(), checksum(&data));
    }

    #[test]
    fn empty_is_stable() {
        assert_eq!(checksum(b""), Rolling::new().finish());
    }
}
